In [1]:
import numpy as np

아래를 신경망 출력이라 가정

In [2]:
a = np.array([0.3, 0.9, 5.0])

이 숫자를 어떻게 해석?

In [3]:
a = np.array([0.3, -0.9, 5.0])

또한 위처럼 - 부호를 가질 수도 있음.

분류 (classification) 문제의 경우 가장 큰 값을 선택하면 되기는 하지만...

즉, 위의 경우 class 가 2. 숫자를 해석하기가 애매함

Motivation: 위의 값을 확률처럼 해석하면 좋을텐데 ?!

Softmax의 등장

In [4]:
a

array([ 0.3, -0.9,  5. ])

In [5]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [6]:
y = softmax(a)

In [7]:
print(y)

[0.0089889 0.0027074 0.9883037]


In [8]:
np.sum(y)

1.0

확률처럼 더하면 1이 되고, 모두가 양수로 변환되었음을 확인 !

Numerically stable Softmax

위의 softmax() 함수는 완벽하지만 컴퓨터로 계산할 때 결함이 있을 수 있음.

softmax()에 사용되는 지수함수 exp()는 넣는 값이 조금만 커져도 아주 큰 값을 뱉어줌.

컴퓨터는 표현할 수 있는 수의 범위가 한정 되므로 이 문제를 개선한 안전한 softmax() 함수를 만들어 보자.

In [9]:
a = np.array([1010, 1000, 990]) #큰 수 준비

In [10]:
y = softmax(a)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


In [11]:
print(y)  #제대로 계산되지 않음.

[nan nan nan]


In [12]:
def stable_softmax(a):
    c = np.max(a)
    exp_a = np.exp(a-c)   #개선
    sum_exp_a = sum(np.exp(a-c))
    y = exp_a/sum_exp_a
    return y

In [13]:
y = stable_softmax(a)

In [14]:
print(y)

[9.99954600e-01 4.53978686e-05 2.06106005e-09]


In [15]:
np.sum(y)   # 마찬가지로 더하면 1을 출력!

1.0